### ISSUE TITLE
Spelling mistake in header name in Uploader.js

### ISSUE THREAD

**Issue by crispy-cat** [ShadowLp174/revolt-uploader#1]
On line 28 of Uploader.js one of the header names is spelled `"Content-Lenght"`

**Comment by ShadowLp174** [comment]
Oh yeah lmao... I actually copied the header bit from stackoverflow

**Comment by ShadowLp174** [comment]
I'm going to fix this soon:tm: when the holidays start and I've got a bit more time. I'm too scared to delete it without testing rn

**Comment by austinhuang0131** [comment]
should be closed by https://github.com/ShadowLp174/revolt-uploader/commit/db812594d35297230e3b68540a5b4d62cd175693

**Comment by ShadowLp174** [comment]
You're right, should've closed this a long time ago xD
